pedcon/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Wagtail Imports
from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedcon_main.urls')),
    # path('', include('blog.urls')),

    # Wagtail urls
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('blog/', include(wagtail_urls)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedcon_main/urls.py
"""Defines URL patterns for pedcon."""

from django.urls import path
from . import views

app_name = 'pedcon_main'
urlpatterns = [

    # Home Page
    path('', views.index, name='index'),
    # About us
    path('about_us/', views.about_us, name='about_us'),
    # Services page
    path('services/', views.services, name='services'),
    # Forms page
    path('forms/', views.forms, name='forms'),
    # Faq page
    path('faq/', views.faq, name='faq'),
    # Local professionals page
    path('local_professionals/', views.local_professionals,
         name='local_professionals'),
    # Helpful links page
    path('helpful_links/', views.helpful_links, name='helpful_links'),
    # Recommended product page
    path('recommended_products/', views.recommended_products,
         name='recommended_products'),
    # Contact page
    path('contact/', views.contact, name='contact'),
    # Privacy policy page
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # Clinic policy page
    path('clinic_policy/', views.clinic_policy, name='clinic_policy'),
    # Success page
    path('success/', views.success, name='success'),



    # *************** urls for individual staff pages ***************

    # About Deana page
    path('about_us_deana', views.about_us_deana, name='about_us_deana'),
    # About Lisa berry page
    path('lisa-berry', views.lisa_berry, name='lisa-berry'),
    # About Briana page
    path('briana-picht', views.briana_picht, name='briana-picht'),
    # About Lisa Bergeson page
    path('lisa-bergeson', views.lisa_bergeson, name='lisa-bergeson'),
    # About Jennifer Shrum page
    path('jennifer-shrum', views.jennifer_shrum, name='jennifer-shrum'),
    # About Paula Worley page
    path('paula-worley', views.paula_worley, name='paula-worley'),
    # About Trisha Morris page
    path('trisha-morris', views.trisha_morris, name='trisha-morris'),
    # About Cathy Pickert page
    path('cathy-pickert', views.cathy_pickert, name='cathy-pickert'),
    # About Suzanne Remy page
    path('suzanne-remy', views.suzanne_remy, name='suzanne-remy'),
    # About Jennifer Vennart page
    path('jennifer-vennart', views.jennifer_vennart, name='jennifer-vennart'),
    # About Casey Fitzgerald page
    path('casey-fitzgerald', views.casey_fitzgerald, name='casey-fitzgerald'),
    # About Kelly Daugherty page
    path('kelly-daugherty', views.kelly_daugherty, name='kelly-daugherty'),
    # About Kaylan Campain page
    path('kaylan-campain', views.kaylan_campain, name='kaylan-campain'),
    # About Allison Casey page
    path('allison-casey', views.allison_casey, name='allison-casey'),
    # About Taylor Sjorgen page
    path('taylor-sjorgen', views.taylor_sjorgen, name='taylor-sjorgen'),



    # *************** urls for form pages ***************

    # Practice form page
    # path('practice_form/', views.PracticeFormView.as_view(), name='practice_form'),
    # Client information form page
    path('client_info_form/', views.CIFormView.as_view(), name='client_info_form'),
    # Payment policy form page
    path('payment_policy_form/', views.PaymentPolicyFormView.as_view(),
         name='payment_policy_form'),
    # Cancellation policy form page
    path('cancellation_policy_form/', views.CancellationPolicyFormView.as_view(),
         name='cancellation_policy_form'),
    # Pediatric history form page
    path('pediatric_hx_form/', views.PediatricHxFormView.as_view(),
         name='pediatric_hx_form'),
    # Adult history form page
    path('adult_hx_form/', views.AdultHxFormView.as_view(), name='adult_hx_form'),
    # Speech Language history form page
    path('speech_language_hx_form/', views.SpeechLanguageHxFormView.as_view(),
         name='speech_language_hx_form'),
    # Release of information history form page
    path('roi_form/', views.ROIFormView.as_view(), name='roi_form'),
    # SSP form page
    path('ssp_form/', views.SSPFormView.as_view(), name='ssp_form'),
    # Hipaa form page
    path('hipaa_form/', views.HipaaFormView.as_view(), name='hipaa_form'),



    # *************** urls for PDF views ***************

    # Practice PDF view
    # path('pdf_view/<int:pk>/', views.ViewPDF.as_view(), name='pdf_view'),
    # Client info PDF view
    path('ci_pdf_view/<int:pk>/', views.ViewCIPDF.as_view(), name='ci_pdf_view'),
    # Payment policy PDF view
    path('pp_pdf_view/<int:pk>/', views.ViewPPPDF.as_view(), name='pp_pdf_view'),
    # Cancellation Policy PDF view
    path('cancel_pdf_view/<int:pk>/',
         views.ViewCancelPDF.as_view(), name='cancel_pdf_view'),
    # ROI PDF view
    path('roi_pdf_view/<int:pk>/', views.ViewROIPDF.as_view(), name='roi_pdf_view'),
    # Pediatric History PDF view
    path('pediatric_hx_pdf_view/<int:pk>/',
         views.ViewPedHxPDF.as_view(), name='pediatric_hx_pdf_view'),
    # Adult History PDF view
    path('adult_hx_pdf_view/<int:pk>/',
         views.ViewAdultHxPDF.as_view(), name='adult_hx_pdf_view'),
    # Speech Language History PDF view
    path('speech_lang_hx_pdf_view/<int:pk>/',
         views.ViewSpeechLangHxPDF.as_view(), name='speech_lang_hx_pdf_view'),
    # Safe and Sound PDF view
    path('ssp_pdf_view/<int:pk>/', views.ViewSSPPDF.as_view(), name='ssp_pdf_view'),
    # Hipaa PDF view
    path('hipaa_pdf_view/<int:pk>/',
         views.ViewHipaaPDF.as_view(), name='hipaa_pdf_view'),

]

pedcon_main/views.py
# My file imports:
from .forms import *
from .models import *
from .utils import *

# Django file imports:
from django.views.generic import View  # for class based views
from django.http import Http404  # allows me to force 404 page when needed
from django.conf import settings  # for sending email in contact page
from django.core.mail import EmailMessage  # for sending email in contact page
from django.core import validators
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import FileResponse, Http404



# # Practice form processing (see .utils for Mixin)
# class PracticeFormView(ProcessFormMixin, View):
#     form_class = PracticeForm
#     initial = {'key': 'value'}
#     template_name = 'pedcon_main/practice_form.html'
#     to_url = '/pdf_view/'

# # renders practice information to PDF & sends email of PDF
# class ViewPDF(CreatePdfMixin, EmailPdfMixin, View):
#     model = PracticeInformation
#     template = 'pedcon_main/practice_pdf_template.html'


# Client info form processing (see .utils for Mixin)
class CIFormView(ProcessFormMixin, View):
    form_class = ClientInformationForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/ci_form.html'
    to_url = '/ci_pdf_view/'

# renders client information to PDF & sends email of PDF


class ViewCIPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = ClientInformation
    template = 'pedcon_main/client_info_pdf_template.html'


# Payment policy form processing (see .utils for Mixin)
class PaymentPolicyFormView(ProcessFormMixin, View):
    form_class = PaymentPolicyForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/pp_form.html'
    to_url = '/pp_pdf_view/'

# renders payment policy information to PDF & sends email of PDF


class ViewPPPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = PaymentPolicyInformation
    template = 'pedcon_main/payment_policy_pdf_template.html'


# Cancellation policy form processing (see .utils for Mixin)
class CancellationPolicyFormView(ProcessFormMixin, View):
    form_class = CancellationPolicyForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/can_pol_form.html'
    to_url = '/cancel_pdf_view/'

# renders cancellation policy information to PDF & sends email of PDF


class ViewCancelPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = CancellationPolicyInformation
    template = 'pedcon_main/cancellation_pdf_template.html'


# Pediatric history form processing (see .utils for Mixin)
class PediatricHxFormView(ProcessFormMixin, View):
    form_class = PedHxForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/pediatric_hx_form.html'
    to_url = '/pediatric_hx_pdf_view/'

# renders pediatric history information to PDF & sends email of PDF


class ViewPedHxPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = PediatricHistoryInformation
    template = 'pedcon_main/pediatric_hx_pdf_template.html'


# Adult history form processing (see .utils for Mixin)
class AdultHxFormView(ProcessFormMixin, View):
    form_class = AdultHxForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/adult_hx_form.html'
    to_url = '/adult_hx_pdf_view/'

# renders adult history information to PDF & sends email of PDF


class ViewAdultHxPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = AdultHistoryInformation
    template = 'pedcon_main/adult_hx_pdf_template.html'


# Speech language history form processing (see .utils for Mixin)
class SpeechLanguageHxFormView(ProcessFormMixin, View):
    form_class = SpeechLanguageHxForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/speech_language_hx_form.html'
    to_url = '/speech_lang_hx_pdf_view/'

# renders speech language history information to PDF & sends email of PDF


class ViewSpeechLangHxPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = SpeechLanguageHxInformation
    template = 'pedcon_main/speech_lang_hx_pdf_template.html'


# Release of information form processing (see .utils for Mixin)
class ROIFormView(ProcessFormMixin, View):
    form_class = ROIForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/roi_form.html'
    to_url = '/roi_pdf_view/'

# renders release of information to PDF & sends email of PDF


class ViewROIPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = ReleaseOfInformation
    template = 'pedcon_main/roi_pdf_template.html'


# Safe and sound form processing (see .utils for Mixin)
class SSPFormView(ProcessFormMixin, View):
    form_class = SSPForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/ssp_form.html'
    to_url = '/ssp_pdf_view/'

# renders SSP information to PDF & sends email of PDF


class ViewSSPPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = SafeAndSoundInformation
    template = 'pedcon_main/safe_and_sound_pdf_template.html'


# Hipaa form processing (see .utils for Mixin)
class HipaaFormView(ProcessFormMixin, View):
    form_class = HipaaForm
    initial = {'key': 'value'}
    template_name = 'pedcon_main/hipaa_form.html'
    to_url = '/hipaa_pdf_view/'

# renders SSP information to PDF & sends email of PDF


class ViewHipaaPDF(CreatePdfMixin, EmailPdfMixin, View):
    model = HipaaInformation
    template = 'pedcon_main/hipaa_pdf_template.html'


# Contact form view. Processes and sends content of contact form
def contact(request):
    """The contact page for pedcon."""
    form = ContactForm(request.POST)
    if request.method == 'POST':

        if form.is_valid():

            subject = 'Contact Form Submission'
            message_first_name = request.POST['first_name']
            message_last_name = request.POST['last_name']
            message_email = request.POST['email']
            message_phone = request.POST['phone']
            message_subject = request.POST['subject']
            message = request.POST['message']
            msg = f'Name: {message_first_name} {message_last_name} \n' \
                  f'Email: {message_email} \n'\
                  f'Phone: {message_phone} \n'\
                  f'Subject: {message_subject} \n'\
                  f'Message: {message} \n'
            recipients = ['info@pediatricconnectionsot.com', ]
            # recipients = ['gmlesher@gmail.com',]
            email = EmailMessage(
                subject, msg, settings.EMAIL_HOST_USER, recipients)
            email.send(fail_silently=True)

            '''Use below code for sending to multiple recipients with sendgrid 
            unless sendgrid has a better solution'''
            # recipients = ['info@pediatricconnectionsot.com', 'glesher@garrettlesher.com',]
            '''# Bcc not supported by sendgrid. Workaround is to loop through list 
            of recipients and send them an individual email. Not efficient with 
            large # of recipients, ok for this use case.'''
            # for recipient in recipients:
            #     email = EmailMessage(subject, msg, settings.EMAIL_HOST_USER, [recipient])
            #     email.send(fail_silently=True)
            return render(request, 'pedcon_main/contact.html', {'message_first_name': message_first_name})
    else:
        form = ContactForm()
    return render(request, 'pedcon_main/contact.html', {'form': form})


def index(request):
    """The home page for pedcon."""
    return render(request, 'pedcon_main/index.html')


def about_us(request):
    """The about us page for pedcon."""
    return render(request, 'pedcon_main/about_us.html')


def about_us_deana(request):
    """The about us Deana page for pedcon."""
    return render(request, 'pedcon_main/about_us_deana.html')


def lisa_berry(request):
    """The about us Lisa berry page for pedcon."""
    return render(request, 'pedcon_main/lisa-berry.html')


def briana_picht(request):
    """The about us Briana Picht page for pedcon."""
    return render(request, 'pedcon_main/briana-picht.html')


def lisa_bergeson(request):
    """The about us Lisa bergeson page for pedcon."""
    return render(request, 'pedcon_main/lisa-bergeson.html')


def jennifer_shrum(request):
    """The about us Jennifer Shrum page for pedcon."""
    return render(request, 'pedcon_main/jennifer-shrum.html')


def paula_worley(request):
    """The about us Paula Worley page for pedcon."""
    return render(request, 'pedcon_main/paula-worley.html')


def trisha_morris(request):
    """The about us Trisha Morris page for pedcon."""
    return render(request, 'pedcon_main/trisha-morris.html')


def cathy_pickert(request):
    """The about us Cathy Pickert page for pedcon."""
    return render(request, 'pedcon_main/cathy-pickert.html')


def suzanne_remy(request):
    """The about us Suzanne Remy page for pedcon."""
    return render(request, 'pedcon_main/suzanne-remy.html')


def jennifer_vennart(request):
    """The about us Jennifer Vennart page for pedcon."""
    return render(request, 'pedcon_main/jennifer-vennart.html')


def casey_fitzgerald(request):
    """The about us Casey Fitzgerald page for pedcon."""
    return render(request, 'pedcon_main/casey-fitzgerald.html')


def kelly_daugherty(request):
    """The about us Kelly Daugherty page for pedcon."""
    return render(request, 'pedcon_main/kelly-daugherty.html')


def kaylan_campain(request):
    """The about us Kaylan Campain page for pedcon."""
    return render(request, 'pedcon_main/kaylan-campain.html')


def allison_casey(request):
    """The about us Allison Casey page for pedcon."""
    return render(request, 'pedcon_main/allison-casey.html')


def taylor_sjorgen(request):
    """The about us Taylor Sjorgen page for pedcon."""
    return render(request, 'pedcon_main/taylor-sjorgen.html')


def services(request):
    """The services page for pedcon."""
    return render(request, 'pedcon_main/services.html')


def forms(request):
    """The forms page for pedcon."""
    return render(request, 'pedcon_main/forms.html')


def faq(request):
    """The faq page for pedcon."""

pedcon_main/templates/pedcon_main/base.html
{% load static wagtailuserbar wagtailcore_tags %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <title>Pediatric Connections</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="{% static 'pedcon_main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'pedcon_main/css/styles.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'pedcon_main/images/favicon.png' %}"/>
    
    {% block extra_css %}
      {# Override this in templates to add extra stylesheets #}
    {% endblock %}

  </head>
  
  <body>
    {% wagtailuserbar %}
    
    <header class="header">
      
      <nav id="header-nav" class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-center">

          <!--Navbar header-->
        <a href="{% url 'pedcon_main:index' %}" class="navbar-brand d-flex w-25 mr-auto" id="logo"><img style="width: 170px" src="{% static 'pedcon_main/images/logo.png' %}" alt="logo">
        </a>

        <!--Build collapsible button for small screen size-->
        <button id="toggler" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-items" aria-controls="header-items" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <!--Populate collapsible button with information-->
        <div class="navbar-collapse collapse w-50" id="header-items">
          <ul class="navbar-nav w-100 justify-content-center">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'pedcon_main:index' %}">Home <span class="sr-only">(current)</span></a><hr class="d-block d-lg-none d-xl-none">
            </li>
            <li class="nav-item">
              <a class="nav-link aboutus" href="{% url 'pedcon_main:about_us' %}">About Us</a><hr class="d-block d-lg-none d-xl-none">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pedcon_main:services' %}">Services</a><hr class="d-block d-lg-none d-xl-none">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/blog/">Blog</a><hr class="d-block d-lg-none d-xl-none">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pedcon_main:forms' %}">Forms</a><hr class="d-block d-lg-none d-xl-none">
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Resources
              </a><hr class="d-block d-lg-none d-xl-none">
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'pedcon_main:faq' %}">FAQ</a>
                <a class="dropdown-item" href="{% url 'pedcon_main:local_professionals' %}">Local Professionals</a>
                <a class="dropdown-item" href="{% url 'pedcon_main:helpful_links' %}">Helpful Links</a>
                <a class="dropdown-item" href="{% url 'pedcon_main:recommended_products' %}">Recommended Products</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pedcon_main:contact' %}">Contact</a><hr class="d-block d-lg-none d-xl-none">
            </li>
          </ul>

          <!--Hidden search bar in header (for now)-->
          <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>-->
        </div><!-- .collapse .navbar-collapse -->
        <div class="w-25 d-none d-lg-block">
          
        </div>
      </nav><!-- #header-nav -->
    </header>

    {% block content %} {% endblock content %}

    <footer class="panel-footer footer">
      <div class="container">
        <div class="row">
          <section id="hours" class="col-md-4 col-sm-12">
            Mon - Thurs: 8:00am-6:30pm<br>
            Fri: 8:00am-2:00pm<br>
            Sat & Sun: closed<br>
            <hr class="d-block d-md-none d-lg-none d-xl-none">
          </section>
          <section id="address" class="col-md-4 col-sm-12">
            7235 W 162nd Ter<br>
            Stilwell, KS 66085<br>
            <hr class="d-block d-md-none d-lg-none d-xl-none">
          </section>
          <section id="contact-info" class="col-md-4 col-sm-12">
            <a href="tel: 913-257-5808">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.267.98a1.636 1.636 0 0 1 2.448.152l1.681 2.162c.309.396.418.913.296 1.4l-.513 2.053a.636.636 0 0 0 .167.604L8.65 9.654a.636.636 0 0 0 .604.167l2.052-.513a1.636 1.636 0 0 1 1.401.296l2.162 1.681c.777.604.849 1.753.153 2.448l-.97.97c-.693.693-1.73.998-2.697.658a17.47 17.47 0 0 1-6.571-4.144A17.47 17.47 0 0 1 .639 4.646c-.34-.967-.035-2.004.658-2.698l.97-.969z"/>
              </svg>&nbsp; 913-257-5808<br>
            </a>
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-printer-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M5 1a2 2 0 0 0-2 2v1h10V3a2 2 0 0 0-2-2H5z"/>
                <path fill-rule="evenodd" d="M11 9H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1z"/>
                <path fill-rule="evenodd" d="M0 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-2a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2H2a2 2 0 0 1-2-2V7zm2.5 1a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
              </svg> 
              &nbsp; 844-270-5788<br>
              <a href="mailto: info@pediatricconnectionsot.com">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                </svg>
                &nbsp;info@pediatricconnectionsot.com<br></a> 
            <hr class="d-block d-md-none d-lg-none d-xl-none">
          </section>
        </div>
        <div id="social-media-images" class="text-center">
          <a href="https://www.facebook.com/pediatricconnections" target="_blank"><img src="{% static 'pedcon_main/images/facebook_icon.png' %}"></a> 
          <a href="https://www.pinterest.com/pedconnectionso/" target="_blank"><img src="{% static 'pedcon_main/images/pinterest_icon.png' %}"></a> 
          <a href="https://www.instagram.com/pediatricconnectionsot/" target="_blank"><img src="{% static 'pedcon_main/images/instagram_icon.png' %}"></a> 
          <a href="https://www.youtube.com/channel/UC3h0muLW7GSxBr_DdtaLOCg" target="_blank"><img src="{% static 'pedcon_main/images/youtube_icon.png' %}"></a>  
        </div>
        <div id="copyright" class="text-center">
          <!-- &copy; Copyright Pediatric Connections {% now "Y" %}.<br> -->
        <div id="privacy-policy" class="text-center"><a href="{% url 'pedcon_main:privacy_policy' %}">Privacy Policy</a></div>
      </div>
    </footer>

    <script src="{% static 'pedcon_main/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'pedcon_main/js/script.js' %}"></script>
    <script src="{% static 'pedcon_main/js/bootstrap.min.js' %}"></script> 

    {% block extra_js %}
        {# Override this in templates to add extra javascript #}
    {% endblock %}

  </body>
</html>

pedcon_main/templates/pedcon_main/forms.html
{% extends "pedcon_main/base.html" %}
{% load static %}

{% block content %}


  <div class="pageHeading">
    <h1>Forms</h1>
  </div>

  <div class="formsImg"></div>

  <div class="formLinksMopContainer row m-0">
    <div class="formLinks col-md-8">
      <div>
        <h3>Preparing for your first visit</h3>
        <p>
          Please complete all forms and submit online.<br>
          Once all forms and doctor's orders are received, we will contact you about appointment options.  
        </p>
      </div>
      <h5>Mandatory forms for all clients:</h5>
      <ul>
        <!-- add practice form here if necessary -->
        <li><a href="{% url 'pedcon_main:client_info_form' %}">Client Information</a></li>
        <li><a href="{% url 'pedcon_main:payment_policy_form' %}">Payment Policy/HIPAA</a></li>
        <li><a href="{% url 'pedcon_main:cancellation_policy_form' %}">Cancellation Policy</a></li>
      </ul>
      <h5>Additional mandatory forms for pediatric clients:</h5>
      <ul>
        <li><a href="{% url 'pedcon_main:pediatric_hx_form' %}">Pediatric History</a></li>
      </ul>
      <h5>Additional mandatory forms for adult clients:</h5>
      <ul>
        <li><a href="{% url 'pedcon_main:adult_hx_form' %}">Adult History</a></li>
      </ul>
      <h5>Optional forms:</h5>
      <ul>
        <li><a href="{% url 'pedcon_main:speech_language_hx_form' %}">Speech Language History</a></li>
        <li><a href="{% url 'pedcon_main:roi_form' %}">Release of Information</a></li>
        <li><a href="{% url 'pedcon_main:ssp_form' %}">Safe and Sound Protocol</a></li>
      </ul>
    </div>

    <div class="mop col-md-4">
      <h3>Methods of Payment</h3>
      <h5>In Network Insurance Plans</h5>
      <ul>
        <li>Blue Cross Blue Shield</li>
        <li>Tricare</li>
        <li>Kansas Medicaid</li>
        <ul>
          <li>Aetna Better Health of Kansas</li>
          <li>UHC Kancare</li>
          <li>Sunflower (with some stipulations due to high rate of denials)</li>
        </ul>
      </ul>
      <h5>Out of Network Insurance Plans</h5>
      <ul>
        <li>United Health Care</li>
        <li>Blue Cross Blue Shield - Blue Select</li>
        <li>Aetna</li>
        <li>Coventry</li>
        <li>Cigna</li>
        <li>Humana</li>
        <li>Missouri Health Net</li>
        <li>Missouri Medicaid</li>
      </ul><br>
      <p>*Private pay (contact our office for fee schedule)</p>
    </div>
  </div>

{% endblock content %}